# Generated by Django 3.1 on 2021-09-15 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 9, 15, 5, 13, 10, 950323, tzinfo=utc)),
        ),
    ]
