# Generated by Django 3.1 on 2021-08-20 21:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user',
            new_name='my_messages',
        ),
        migrations.RemoveField(
            model_name='contacted',
            name='as_A',
        ),
        migrations.AddField(
            model_name='messages',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='user_to_review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='matricNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_product',
            name='campus',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product_img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='campus',
            field=models.CharField(choices=[('ojo', 'OJO'), ('epe', 'EPE'), ('lasuth', 'LASUTH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='contact',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='quote',
            field=models.CharField(default='yes', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='university',
            field=models.CharField(default='LASU', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 21, 32, 50, 707686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='searchTag',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=80)),
                ('as_buyer', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.user_detail')),
            ],
        ),
    ]
