# Generated by Django 3.1 on 2021-06-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210627_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='user',
            new_name='baseuser',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='campus',
            field=models.CharField(choices=[('ojo', 'OJO'), ('epe', 'EPE'), ('lasuth', 'LASUTH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='university',
            field=models.CharField(default='LASU', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
