# Generated by Django 3.1 on 2021-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210628_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='matricNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
