# Generated by Django 3.1 on 2021-07-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_user_detail_matricno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
