# Generated by Django 3.1 on 2021-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_user_detail_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
    ]
