# Generated by Django 3.1 on 2021-07-11 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20210711_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 16, 16, 20, 146960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
