# Generated by Django 3.1 on 2021-07-13 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20210713_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user',
            new_name='my_messages',
        ),
        migrations.RemoveField(
            model_name='contacted',
            name='as_A',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='as_A',
        ),
        migrations.AddField(
            model_name='messages',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='user_to_review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='as_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviews',
            name='username',
            field=models.CharField(default='False', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 3, 29, 54, 969781, tzinfo=utc)),
        ),
    ]
