# Generated by Django 3.1 on 2021-07-13 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20210713_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_product',
            name='campus',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 7, 32, 56, 584774, tzinfo=utc)),
        ),
    ]
