# Generated by Django 3.1 on 2021-07-24 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20210713_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='contacted',
        ),
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 24, 17, 18, 5, 110861, tzinfo=utc)),
        ),
    ]
