# Generated by Django 3.1 on 2021-07-24 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20210724_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 24, 17, 21, 7, 593335, tzinfo=utc)),
        ),
    ]
