# Generated by Django 3.1 on 2021-07-26 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20210724_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 16, 13, 22, 921204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_product',
            name='searchTag',
            field=models.CharField(max_length=30),
        ),
    ]
