# Generated by Django 3.1 on 2021-07-28 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20210726_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 28, 20, 40, 19, 949285, tzinfo=utc)),
        ),
    ]
