# Generated by Django 3.1 on 2021-07-29 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20210728_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 1, 20, 51, 273703, tzinfo=utc)),
        ),
    ]
