# Generated by Django 3.1 on 2021-08-05 23:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_auto_20210729_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 23, 33, 8, 889563, tzinfo=utc)),
        ),
    ]
