# Generated by Django 3.1 on 2021-08-15 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_auto_20210806_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='product_img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='contact',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='quote',
            field=models.CharField(default='your online market place', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_product',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 13, 3, 8, 766203, tzinfo=utc)),
        ),
    ]
